[platformio]
src_dir = .

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags = -std=gnu++17
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    mathertel/OneButton
